nand: arasan_nfs: Add missing of.h
For !CONFIG_OF_MTD case of.h is missing.
Kbuild system reports error:
drivers/mtd/nand/arasan_nfc.c: In function 'anfc_probe':
drivers/mtd/nand/arasan_nfc.c:794:2: error: implicit declaration of
function 'of_property_read_bool'
[-Werror=implicit-function-declaration]
   nfc->dma = of_property_read_bool(pdev->dev.of_node,

Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>