dmaengine: Fix softip dma test client compilation
Fix the following compile errors when CONFIG_XILINX_DMATEST=y:
error: implicit declaration of function 'put_task_struct'; did you mean 'get_task_cred'? [-Werror=implicit-function-declaration]
| put_task_struct(thread->task);
| ^~~~~~~~~~~~~~~
...
error: implicit declaration of function 'get_task_struct'; did you mean 'get_task_cred'? [-Werror=implicit-function-declaration]
| get_task_struct(thread->task);
| ^~~~~~~~~~~~~~~

This is an upstream issue that was fixed as part of the following
linux-xlnx merge-commit:

commit 818f168696f561c127f161379eb5b8d1835218a2
Merge: 9c2e29b2c81d bebc6082da0a
Author: Michal Simek <michal.simek@xilinx.com>
Date:   Thu Jan 11 13:58:55 2018 +0100

    Merge tag 'v4.14' into master

    Linux 4.14
    Changes:
...
	dma:
	- dmaengine: Fix softip dma test client compilation (by Kedar)
...

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>