xhci: Rename variables related to transfer descritpors
This patch is based on the mainline commit 9ef7fbbb to fix the following
compiling errors:

drivers/usb/host/xhci-ring.c: In function 'xhci_stream_timeout':
drivers/usb/host/xhci-ring.c:962:27: error: 'struct urb_priv' has no member named 'length'
  for (i = 0; i < urb_priv->length; i++) {
                          ^~
drivers/usb/host/xhci-ring.c:963:7: error: incompatible types when assigning to type 'struct xhci_td *' from type 'struct xhci_td'
   td = urb_priv->td[i];
      ^
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>