genirq: change wake_depth log from warning to info level
commit  4ee980ff9761a1df913a58aef501013fb9c52a03 from
https://github.com/MarvellEmbeddedProcessors/linux-marvell.git

Within routine irq_set_irq_wake(), when input parameter "on" is set,
the descriptor structure member wake_depth will be increased, but it
will be reset to 0 if set_irq_wake_real() fail, which happen
when irq chip does not implement the irq_set_wake callback routine.
The irq chip used by the RTC is GIC-400, which does not implement
the irq_set_wake callback routine.
Thus this patch changes the log level from warning to information level
to avoid unnecessary console printing.

Change-Id: I88dce7002b157e8f72a83847ff8bb60710247ea5
Signed-off-by: Victor Gu <xigu@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/42637
Reviewed-by: Marcin Wojtas <mw@semihalf.com>
Reviewed-by: Kostya Porotchkin <kostap@marvell.com>
Tested-by: iSoC Platform CI <ykjenk@marvell.com>
Reviewed-by: Hanna Hawa <hannah@marvell.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>