drm: xilinx: plane fix compiling errors
This compiling error come from the DRM updates from mainline, and so we
need to do the related updates.

drivers/gpu/drm/xilinx/xilinx_drm_plane.c: In function 'xilinx_drm_plane_mode_set':
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:271:31: error: 'struct drm_framebuffer' has no member named 'bits_per_pixel'
 DRM_DEBUG_KMS("bpp: %d\n", fb->bits_per_pixel / 8);
                              ^
include/drm/drmP.h:240:44: note: in definition of macro 'DRM_DEBUG_KMS'
 drm_printk(KERN_DEBUG, DRM_UT_KMS, fmt, ##__VA_ARGS__)
                                           ^~~~~~~~~~~
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:273:48: error: 'struct drm_framebuffer' has no member named 'pixel_format'; did you mean 'format'?
 hsub = drm_format_horz_chroma_subsampling(fb->pixel_format);
                                               ^~~~~~~~~~~~
                                               format
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:274:48: error: 'struct drm_framebuffer' has no member named 'pixel_format'; did you mean 'format'?
 vsub = drm_format_vert_chroma_subsampling(fb->pixel_format);
                                               ^~~~~~~~~~~~
                                               format
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:276:44: error: 'struct drm_framebuffer' has no member named 'pixel_format'; did you mean 'format'?
 for (i = 0; i < drm_format_num_planes(fb->pixel_format); i++) {
                                           ^~~~~~~~~~~~
                                           format
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:279:47: error: 'struct drm_framebuffer' has no member named 'pixel_format'; did you mean 'format'?
  unsigned int cpp = drm_format_plane_cpp(fb->pixel_format, i);
                                              ^~~~~~~~~~~~
                                              format
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:282:36: error: 'struct drm_framebuffer' has no member named 'pixel_format'; did you mean 'format'?
   cpp = xilinx_drm_format_bpp(fb->pixel_format) >> 3;
                                   ^~~~~~~~~~~~
                                   format
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:328:17: error: 'struct drm_framebuffer' has no member named 'pixel_format'; did you mean 'format'?
            fb->pixel_format);
                ^~~~~~~~~~~~
                format

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>