media: xilinx: scaler: Remove a space before ','
Remove a space to fix the error from checkpatch:

./scripts/checkpatch.pl --max-line-length 120 -f xilinx-scaler.c
ERROR: space prohibited before that ',' (ctx:WxW)
+	numerator = fixp_mult(temp , a);
 	                           ^

				   total: 1 errors, 0 warnings, 708 lines checked

Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
(cherry picked from commit 315f0192f1e9ebc0e38ada4bfbcc0ddf1c0c7f11)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>