dmaengine: vdma: rename the conflict function of
xilinx_vdma_channel_set_config

just old axivdma driver can support zc702-zvik-base-trd-2015-4,
we rename xilinx_vdma_channel_set_config function in xilinx_vdma,
so it  can fix build error as follow:

drivers/dma/xilinx/xilinx_dma.o: In function
`xilinx_vdma_channel_set_config':
drivers/dma/xilinx/xilinx_dma.c:2043:
multiple definition of `xilinx_vdma_channel_set_config'
drivers/dma/xilinx/xilinx_vdma.o:/export/disk1T/bsp_work/TI_AM335X/kernel-4.8.x/drivers/dma/xilinx/xilinx_vdma.c:1044:
first defined here
drivers/dma/xilinx/xilinx_dma.o:(___ksymtab+xilinx_vdma_channel_set_config+0x0):
multiple definition of `__ksymtab_xilinx_vdma_channel_set_config'
drivers/dma/xilinx/xilinx_vdma.o:(___ksymtab+xilinx_vdma_channel_set_config+0x0):
first defined here

Signed-off-by: zou cao <cao.zou@windriver.com>
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>