pci: aardvard: set host and device to the same MAX payload size
commit  7ce8f8c52db804157a7bc6689cd0b7db154b3204 from
https://github.com/MarvellEmbeddedProcessors/linux-marvell.git

Since the Aardvard does not implement PCIe root bus, the Linux PCIe
framework will not align the MAX payload size between host and device
for it.
This patch sets host and device to the same MAX payload size in Aardvard
PCIe driver.

Change-Id: I3979397b3af98911c067f7ad384922aa3f05497f
Signed-off-by: Victor Gu <xigu@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/37927
Tested-by: iSoC Platform CI <ykjenk@marvell.com>
Reviewed-by: Evan Wang <xswang@marvell.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>