inphi: fix for `__bad_udelay'
inphi driver failed to build with WAIT() called with value > 200

void WAIT(int delay_cycles)
{
	udelay(delay_cycles * 10);
}

drivers/built-in.o: In function `WAIT':
lx2-linux/drivers/net/phy/inphi.c:190: undefined reference to `__bad_udelay'
lx2-linux/drivers/net/phy/inphi.c:190:(.text+0x26f4bc): relocation truncated to
fit: R_AARCH64_CALL26 against undefined symbol `__bad_udelay'

__bad_udelay is specifically designed on ARM to produce a build failure
when udelay is called with a value > 2000.

Signed-off-by: Meenakshi Aggarwal <meenakshi.aggarwal@nxp.com>
[Xulin: Original patch taken from NXP lx2160a-early-access-bsp0.3.]
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>