memory: ti-emif-sram: remove unused variable
This commit comes from:
  git://git.ti.com/processor-sdk/processor-sdk-linux.git

The newly introduced driver causes a harmless warning for a variable
that was evidently never used:

drivers/memory/ti-emif-pm.c: In function 'ti_emif_remove':
drivers/memory/ti-emif-pm.c:303:17: error: unused variable 'dev' [-Werror=unused-variable]

Fixes: 8428e5ad750d ("memory: ti-emif-sram: introduce relocatable suspend/resume handlers")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Santosh Shilimkar <santosh.shilimkar@oracle.com>
(cherry picked from commit 84a1695a6f925291f301951498fd7b56d3cb40a2)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>