v4l: xilinx: csi2rxss: replace media_entity_init with media_entity_pads_init
This patch is to fix a compiling error according to the mainline commit ab22e77c
as follows:

drivers/media/platform/xilinx/xilinx-csi2rxss.c: In function 'xcsi2rxss_probe':
drivers/media/platform/xilinx/xilinx-csi2rxss.c:1638:8: error: implicit declaration of function 'media_entity_init';
|   ret = media_entity_init(&subdev->entity, 2, xcsi2rxss->pads, 0);
|         ^~~~~~~~~~~~~~~~~

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>