Buildissue: build guest qemu failed kernel/power/suspend.c:100:2: error: implicit declaration of function 'rawspin_unlock_irq'
commit [0d29972245] introduced the breakage.

Signed-off-by: Jiping Ma <jiping.ma2@windriver.com>