ppc: pci: export two symbols
The symbols need to be accesible by modules, for example mpc85xx_edac,
so export them, else build system will report the below errors:

ERROR: ".pci_find_hose_for_OF_device" [drivers/edac/mpc85xx_edac.ko] undefined!
ERROR: ".early_find_capability" [drivers/edac/mpc85xx_edac.ko] undefined!

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>