arm64: zynqmp: Add missing maximum-speed property to usb nodes
commit  8a583ff3440a25b16a76f993d1122b8dfcecb822 from
https://github.com/Xilinx/linux-xlnx.git

Add missing properties to dt node.

Error log:
ERROR: usb maximum-speed not found

Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>