drm: xilinx: plane add drm_modeset_acquire_ctx accordingly
It seems struct drm_modeset_acquire_ctx *ctx has been inserted in the mainline
DRM, so we did the same thing as other drivers to fix the following errors:

drivers/gpu/drm/xilinx/xilinx_drm_plane.c:525:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   .update_plane = xilinx_drm_plane_update,
                   ^~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:525:18: note: (near initialization for 'xilinx_drm_plane_funcs.update_plane')
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:526:19: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
 .disable_plane = xilinx_drm_plane_disable,
                  ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/xilinx/xilinx_drm_plane.c:526:19: note: (near initialization for 'xilinx_drm_plane_funcs.disable_plane')

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>