drm: xilinx: fix ppp compiling error due to drm_framebuffer updates
We can take the related fixes in mainline b00c600e 272725c7 as references

drivers/gpu/drm/xilinx/xilinx_drm_fb.c: In function 'xilinx_drm_fbdev_create':
drivers/gpu/drm/xilinx/xilinx_drm_fb.c:280:58: error: 'struct drm_framebuffer' has no member named 'depth'
 drm_fb_helper_fill_fix(fbi, base_fb->pitches[0], base_fb->depth);
                                                         ^~
drivers/gpu/drm/xilinx/xilinx_drm_fb.c: In function 'xilinx_drm_fb_create':
drivers/gpu/drm/xilinx/xilinx_drm_fb.c:482:2: error: implicit declaration of function 'drm_fb_get_bpp_depth';
did you mean 'xilinx_fb_get_bpp_depth'? [-Werror=implicit-function-declaration]
 drm_fb_get_bpp_depth(mode_cmd->pixel_format, &fb->base.depth,
 ^~~~~~~~~~~~~~~~~~~~
 xilinx_fb_get_bpp_depth
drivers/gpu/drm/xilinx/xilinx_drm_fb.c:482:56: error: 'struct drm_framebuffer' has no member named 'depth'
 drm_fb_get_bpp_depth(mode_cmd->pixel_format, &fb->base.depth,
                                                       ^
drivers/gpu/drm/xilinx/xilinx_drm_fb.c:483:18: error: 'struct drm_framebuffer' has no member named 'bits_per_pixel'
        &fb->base.bits_per_pixel);
                 ^
drivers/gpu/drm/xilinx/xilinx_drm_fb.c:484:15: error: 'struct drm_framebuffer' has no member named 'bits_per_pixel'
 if (!fb->base.bits_per_pixel)
              ^
drivers/gpu/drm/xilinx/xilinx_drm_fb.c:485:11: error: 'struct drm_framebuffer' has no member named 'bits_per_pixel'
  fb->base.bits_per_pixel =
          ^
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>