drivers/fsl_qbman: move out a macro definition from usdpaa scope
There is following compilation error when the CONFIG_FSL_USDPAA is
not set on fsl-e500mc kernel because the QBMAN_ANY_PORTAL_IDX macro
is defined in the USDPAA scope but used outside of it, fix it by
moving out the macro definition from the USDPAA scope.

drivers/staging/fsl_qbman/bman_driver.c:231:13: error:
'QBMAN_ANY_PORTAL_IDX' undeclared (first use in this function)

Signed-off-by: Shan Hai <shan.hai@windriver.com>