cryptodev: fix compile error when enable CONFIG_CRYPTODEV
Fix the following compile error:
error: implicit declaration of function 'aead_request_set_assoc'
error: implicit declaration of function 'crypto_alloc_ablkcipher'
error: too many arguments to function ‘get_user_pages’
error: implicit declaration of function ‘page_cache_release’
error: implicit declaration of function ‘get_unused_fd’

This is due to the old function was used in cryptodev driver,
as the kernel updated, the function in cryptodev was not touched.

To fix this, use the new version of function instead of the
old ones.

Signed-off-by: Liwei Song <liwei.song@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>