drm: xilinx: bypass ctx from xilinx_drm_crtc_page_flip
It seems drm_modeset_acquire_ctx has little codes for other drm apps in the
mainline, so we just give the dummy one as well.

drivers/gpu/drm/xilinx/xilinx_drm_crtc.c:474:15: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .page_flip = xilinx_drm_crtc_page_flip,
               ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/xilinx/xilinx_drm_crtc.c:474:15: note: (near initialization for 'xilinx_drm_crtc_funcs.page_flip')
drivers/gpu/drm/xilinx/xilinx_drm_drv.c: In function 'xilinx_drm_load':

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>