mmc: core: __mmc_set_signal_voltage rename to mmc_set_signal_voltage again
mmc_set_signal_voltage take this function, so follow it

drivers/mmc/core/sd.c: In function 'mmc_sd_init_card':
drivers/mmc/core/sd.c:1018:9: error: implicit declaration of function '__mmc_set_signal_voltage'; did you mean 'mmc_set_signal_voltage'? [-Werror=implicit-function-declaration]
    err = __mmc_set_signal_voltage(host, MMC_SIGNAL_VOLTAGE_180);
          ^~~~~~~~~~~~~~~~~~~~~~~~
          mmc_set_signal_voltage

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>