drm: xilinx: crtc: update the destroy with static
Since xilinx_drm_crtc_destroy is a structure member, it should be static.
And integrate the compiling error the SDK Merge commit

drivers/gpu/drm/xilinx/xilinx_drm_crtc.c: In function 'xilinx_drm_crtc_cancel_page_flip':
drivers/gpu/drm/xilinx/xilinx_drm_crtc.c:311:14: error: 'struct drm_pending_event' has no member named 'destroy'
   event->base.destroy(&event->base);
              ^
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>