usb: dwc3: otg: fix conflict function for zynqmp
drivers/usb/dwc3/gadget.c:595:5: error: conflicting types for '__dwc3_gadget_ep_enable'
 int __dwc3_gadget_ep_enable(struct dwc3_ep *dep,
     ^~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/dwc3/otg.c: In function 'sleep_main_thread_timeout':
drivers/usb/dwc3/otg.c:111:6: error: implicit declaration of function 'signal_pending'; did you mean 'timer_pending'? [-Werror=implicit-function-declaration]
  if (signal_pending(current)) {
      ^~~~~~~~~~~~~~
      timer_pending
drivers/usb/dwc3/otg.c: In function 'otg_main_thread':
drivers/usb/dwc3/otg.c:1315:2: error: implicit declaration of function 'allow_signal'; did you mean 'alloc_uid'? [-Werror=implicit-function-declaration]
  allow_signal(SIGINT);
  ^~~~~~~~~~

The mainline __dwc3_gadget_ep_enable has dropped the redundant parameters, and
signal related function declaration change, so do we.

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>